nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

npmScopes:
  harness:
    npmRegistryServer: https://npm.pkg.github.com
    npmAlwaysAuth: true
    npmAuthToken: HARNESSTOKEN